client: sources/client.c sources/common.c headers/client.h headers/common.h headers/raw.h
		gcc -pthread -o client sources/client.c sources/common.c headers/client.h headers/common.h headers/raw.h -lncurses
